### ISSUE TITLE
Github enterprise 

### ISSUE THREAD

**Issue by SimenB** [mattbrictson/chandler#17]
Hiya! 

Is it possible to use this with GH Enterprise? I don't know enough Ruby (one Rails course at school years ago is my only experience with it) to say either way, but this seems to be geared towards public GH: https://github.com/mattbrictson/chandler/blob/master/lib/chandler/github.rb#L30-L32

**Comment by SimenB** [comment]
@mattbrictson doing `chandler push  --dry-run` lists out a bunch of tags, but doing `chandler push --github https://github.schibsted.io/finn/express-base` gives `Skip https://github.schibsted.io/finn/express-base (no https://github.schibsted.io/finn/express-base entry in CHANGELOG.md)` which seems to come from looking for tags?

Is `--github` buggy?

**Comment by mattbrictson** [comment]
Hi, thanks for the question. Right now GitHub Enterprise is not supported.

We use the octokit gem to connect to the GitHub API, which [does support Enterprise](https://github.com/octokit/octokit.rb#working-with-github-enterprise), but it requires some extra setup. Further, as you noticed, we make some assumptions in Chandler itself about the format of GitHub URLs that ties us to the public version.

I think it shouldn't be too hard to add GH Enterprise support to Chandler. However I don't currently have access to an Enterprise installation, so I'm probably not the best developer to work on this. I'll add a "you can help" label to encourage other contributors to step in. Would you be interested in taking a shot at this?

**Comment by SimenB** [comment]
I haven't touched ruby in years, hopefully someone will step up! Would love to use this

**Comment by mattbrictson** [comment]
Closed via #19
