### ISSUE TITLE
(Optional) replace full GH issue links with just #NUMBER

### ISSUE THREAD

**Issue by szpak** [mattbrictson/chandler#33]
To have valid links in CHANGELOG.md to GitHub issues (and PRs) it is required to have full URL in markdown `[#1](https://github.com/mattbrictson/chandler/issues/1)`. In GH release notes it is enough to have just `#1`. While full link renders fine in GH release notes in a situation you have new release notifications in an (old shool) text form (e.g. with Sibbell which in addition wraps the links) the output is clumsy.

> - Auto drop repository after release - [#37](http://link.sibbell.com/wf/click?upn=9lQbz3uT2dCyDMxUSbiPZtHZep-2FrpXs70v2GbDgI01GEukSTVJy6RKboOVHZ-2F702fn97YGkZiCM6aj3qnZLmobJhDodXKTXrT978tTZhxQE-3D_hV8QMVkInQ3dQdGB9iiivltWHKstFQp04LLVCUyh9UhyABedktGQFTY0yHy1bpOemI3nRtK0xWDRTlUgUHYTiczeXfUxgjnVgk99Avl7b6VksRWT9pEfUiZaEZDVQaT-2FT6xN9RbqhNXz5V1vgEKy7XAcCJCqkJKMHi3OohMnlpUmk6ygsID5MswWCxMdfKzJ9-2FpguFWi50hAdxGPTB-2FQkw-3D-3D
>  - Rename "promote" operation to "release" - [#50](http://link.sibbell.com/wf/click?upn=9lQbz3uT2dCyDMxUSbiPZtHZep-2FrpXs70v2GbDgI01GEukSTVJy6RKboOVHZ-2F702fn97YGkZiCM6aj3qnZLmoTiOBMxOp1ZVzQxyFLEUaYc-3D_hV8QMVkInQ3dQdGB9iiivltWHKstFQp04LLVCUyh9UhyABedktGQFTY0yHy1bpOeHLErXMoM8VJCGJWY6LPWXY2Bivoear9dvGCd9fxMxheS2gZvwE54H5sVBzOVq8VifTL-2BQ-2FmuqzTiHPL39C6g0y-2F38NeZ7K0KAyM7JKiMcTnuPgsPaZWvguupiIByRhCQCJxWcrLYtpUgidN3Fba7-2FA-3D-3D

instead of just:
> - Auto drop repository after release - #37
> - Rename "promote" operation to "release" - #50

It would be nice to (on demand) replace full links to own issues with just numbers during export.

**Comment by mattbrictson** [comment]
Interesting idea. Thanks for the feature suggestion!

I think this is probably beyond the scope of Chandler as I envision it right now. It would involve a level of Markdown munging that feels out of place. Perhaps if Chandler some day gains a plugin system, this would be a candidate for a third-party custom plugin.
