### ISSUE TITLE
Tag-Prefix does not work as expected

### ISSUE THREAD

**Issue by PatrikSteuer** [mattbrictson/chandler#35]
I have a changelog with following content:
```
## [1.0](https://github.wdf.sap.corp/iot/nGrinderTools/tree/ms/1.0) (2017-04-05)
## [ms/1.0](https://github.wdf.sap.corp/iot/nGrinderTools/tree/ms/1.0) (2017-04-05)
```
Furthermore I have following tag:
* ms/1.0

I would expect that at least one of these changelog entries would be pushed to the release notes. Nevertheless I get following message: 
```
chandler push --tag-prefix ms/ --dry-run
Skip ms/ (no ms/ entry in CHANGELOG.md)```

**Comment by mattbrictson** [comment]
Can you try:

```
chandler push --tag-prefix=ms/ --dry-run
```

**Comment by PatrikSteuer** [comment]
... thanks, it seems as I was just to stupid to read the documentation ... great tool btw!
