### ISSUE TITLE
Ignore missing versions

### ISSUE THREAD

**Issue by jhalterman** [mattbrictson/chandler#5]
When running `chandler push` on a changelog, there might be some versions that I have tags for which aren't present in the changelog. It would be nice if I could have chandler ignore the missing versions in the changelog and just push what it can. Currently I get an error, like:

```
/Users/jonathan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/chandler-0.1.2/lib/chandler/changelog.rb:35:in `block in fetch': Couldn’t find 0.2.1 in CHANGELOG.md (Chandler::Changelog::NoMatchingVersion)
```

**Comment by mattbrictson** [comment]
Yes, I can see this being useful. I'll work on this maybe tomorrow.

**Comment by jhalterman** [comment]
I should mentions, the opposite could be true as well - changelog stuff with missing tags. We should probably be able to avoid errors there as well.

**Comment by mattbrictson** [comment]
Yes, I believe Chandler already ignores any extra stuff in the CHANGELOG. Please open another issue if you find this not to be the case.
